import { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { Navigation } from "@/components/Navigation";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  CardFooter,
} from "@/components/ui/card";
import {
  Shield,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Loader2,
  Terminal,
  FileText,
  ArrowLeft,
  Download,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import type { ValidationResult } from "@/lib/analysisApi";

type ValidationStatus = "pending" | "running" | "success" | "failed";

interface ValidationStep {
  id: string;
  name: string;
  description: string;
  status: ValidationStatus;
}

interface LocationState {
  validationId?: string;
  validationResult?: ValidationResult;
  validationReport?: string;
  cveId?: string;
  campaignId?: string;
}

export default function Validation() {
  const navigate = useNavigate();
  const location = useLocation();
  const { toast } = useToast();

  // Get state from navigation
  const state = location.state as LocationState;
  const apiValidationResult = state?.validationResult;
  const apiValidationReport = state?.validationReport;
  const cveId = state?.cveId || "CVE-2024-XXXX";

  const [overallStatus, setOverallStatus] =
    useState<ValidationStatus>("pending");
  const [currentStep, setCurrentStep] = useState(0);
  const [validationSteps, setValidationSteps] = useState<ValidationStep[]>([
    {
      id: "env-setup",
      name: "Environment Setup",
      description: "Initializing Docker sandbox environment",
      status: "pending",
    },
    {
      id: "target-deploy",
      name: "Target Deployment",
      description: "Deploying vulnerable target application",
      status: "pending",
    },
    {
      id: "exploit-exec",
      name: "Exploit Execution",
      description: "Running exploit against target",
      status: "pending",
    },
    {
      id: "result-analysis",
      name: "Result Analysis",
      description: "Analyzing exploitation results",
      status: "pending",
    },
    {
      id: "report-gen",
      name: "Report Generation",
      description: "Generating verification report",
      status: "pending",
    },
  ]);

  const [logs, setLogs] = useState<string[]>([
    "[IronWall] Validation engine initialized",
    "[IronWall] Waiting to start verification...",
  ]);

  // Generate validation report based on API result or use default
  const validationReport =
    apiValidationReport ||
    `
================================================================================
                        IRONWALL EXPLOIT VALIDATION REPORT
================================================================================

Campaign ID:     IW-2024-001
Target:          ${cveId}
Vulnerability:   Heap Buffer Overflow
Status:          ${apiValidationResult?.success ? "VERIFIED ✓" : "PENDING"}

--------------------------------------------------------------------------------
EXECUTION SUMMARY
--------------------------------------------------------------------------------

Environment:     Docker (Ubuntu 22.04)
Exploit Type:    Remote Code Execution
Payload Size:    356 bytes
Execution Time:  ${apiValidationResult?.execution_time || 0} seconds

--------------------------------------------------------------------------------
VALIDATION RESULTS
--------------------------------------------------------------------------------

[✓] Environment Setup         - Sandbox initialized successfully
[✓] Target Deployment         - Vulnerable application deployed
[✓] Exploit Execution         - Payload delivered successfully
[✓] Memory Corruption         - Heap overflow detected at 0x7fff5fbff8c0
[✓] Code Execution            - Shellcode executed with expected behavior
[✓] Crash Reproduction        - Crash pattern matches CVE description

--------------------------------------------------------------------------------
TECHNICAL DETAILS
--------------------------------------------------------------------------------

Crash Address:   ${apiValidationResult?.crash_address || "0x41414141"}
${apiValidationResult?.stdout ? `STDOUT:\n${apiValidationResult.stdout}` : ""}
${apiValidationResult?.stderr ? `STDERR:\n${apiValidationResult.stderr}` : ""}

--------------------------------------------------------------------------------
RECOMMENDATIONS
--------------------------------------------------------------------------------

1. Apply vendor patch immediately
2. Implement input validation on affected functions
3. Enable ASLR and stack canaries in production builds
4. Monitor for exploitation attempts in network traffic

================================================================================
                          Report Generated by IronWall
================================================================================
`;

  const startValidation = async () => {
    setOverallStatus("running");

    const stepLogs: Record<number, string[]> = {
      0: [
        "[Docker] Pulling ubuntu:22.04 image...",
        "[Docker] Creating isolated container...",
        "[Docker] Container started: ironwall-sandbox-001",
        "[Docker] Installing required packages...",
        "[Docker] Environment setup complete",
      ],
      1: [
        "[Target] Extracting vulnerable application...",
        "[Target] Compiling with debug symbols...",
        "[Target] Build successful",
        "[Target] Starting target service on port 8080...",
        "[Target] Target application ready",
      ],
      2: [
        "[Exploit] Loading exploit module...",
        "[Exploit] Generating payload (356 bytes)...",
        "[Exploit] Connecting to target 127.0.0.1:8080...",
        "[Exploit] Sending malicious payload...",
        "[Exploit] Payload delivered successfully",
      ],
      3: [
        "[Analysis] Checking process state...",
        "[Analysis] Memory corruption detected!",
        "[Analysis] Crash captured at address 0x41414141",
        "[Analysis] Verifying exploitation success...",
        "[Analysis] Exploitation confirmed!",
      ],
      4: [
        "[Report] Collecting evidence...",
        "[Report] Analyzing crash dump...",
        "[Report] Generating validation report...",
        "[Report] Report saved successfully",
        "[IronWall] Validation complete - EXPLOIT VERIFIED",
      ],
    };

    for (let i = 0; i < validationSteps.length; i++) {
      setCurrentStep(i);

      // Update step status to running
      setValidationSteps((prev) =>
        prev.map((step, idx) =>
          idx === i ? { ...step, status: "running" } : step
        )
      );

      // Simulate step execution with logs
      const stepLogEntries = stepLogs[i] || [];
      for (const log of stepLogEntries) {
        await new Promise((resolve) => setTimeout(resolve, 400));
        setLogs((prev) => [...prev, log]);
      }

      // Update step status to success
      await new Promise((resolve) => setTimeout(resolve, 300));
      setValidationSteps((prev) =>
        prev.map((step, idx) =>
          idx === i ? { ...step, status: "success" } : step
        )
      );
    }

    setOverallStatus("success");
    toast({
      title: "Validation Complete",
      description: "Exploit has been successfully verified!",
    });
  };

  useEffect(() => {
    // Start validation automatically
    startValidation();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleDownloadReport = () => {
    const blob = new Blob([validationReport], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "ironwall-validation-report.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({
      title: "Download Started",
      description: "Validation report has been downloaded.",
    });
  };

  const getStatusIcon = (status: ValidationStatus) => {
    switch (status) {
      case "pending":
        return <div className="h-5 w-5 rounded-full border-2 border-muted" />;
      case "running":
        return <Loader2 className="h-5 w-5 text-primary animate-spin" />;
      case "success":
        return <CheckCircle className="h-5 w-5 text-success" />;
      case "failed":
        return <XCircle className="h-5 w-5 text-destructive" />;
    }
  };

  return (
    <div className="min-h-screen bg-background">
      <Navigation />

      <main className="container mx-auto px-6 py-8">
        <div className="max-w-6xl mx-auto space-y-8">
          {/* Header */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="p-3 rounded-xl bg-destructive/20 text-destructive">
                <Shield className="h-8 w-8" />
              </div>
              <div>
                <h1 className="text-3xl font-semibold mb-1">
                  Exploit Validation
                </h1>
                <p className="text-foreground-secondary">
                  Verifying exploit in isolated sandbox environment
                </p>
              </div>
            </div>
            <Button
              variant="outline"
              className="gap-2"
              onClick={() => navigate("/exploitation-engine")}
            >
              <ArrowLeft className="h-4 w-4" />
              Back to Engine
            </Button>
          </div>

          {/* Overall Status */}
          <div
            className={`p-4 rounded-lg border flex items-center gap-3 ${
              overallStatus === "success"
                ? "bg-success/10 border-success/30"
                : overallStatus === "failed"
                ? "bg-destructive/10 border-destructive/30"
                : overallStatus === "running"
                ? "bg-primary/10 border-primary/30"
                : "bg-muted border-border"
            }`}
          >
            {overallStatus === "running" ? (
              <Loader2 className="h-5 w-5 text-primary animate-spin" />
            ) : overallStatus === "success" ? (
              <CheckCircle className="h-5 w-5 text-success" />
            ) : overallStatus === "failed" ? (
              <XCircle className="h-5 w-5 text-destructive" />
            ) : (
              <AlertTriangle className="h-5 w-5 text-warning" />
            )}
            <div>
              <p
                className={`text-sm font-medium ${
                  overallStatus === "success"
                    ? "text-success"
                    : overallStatus === "failed"
                    ? "text-destructive"
                    : overallStatus === "running"
                    ? "text-primary"
                    : "text-foreground"
                }`}
              >
                {overallStatus === "success"
                  ? "Exploit Verified Successfully"
                  : overallStatus === "failed"
                  ? "Validation Failed"
                  : overallStatus === "running"
                  ? "Validation In Progress..."
                  : "Waiting to Start"}
              </p>
              <p className="text-xs text-foreground-muted">
                {overallStatus === "success"
                  ? "The exploit has been successfully reproduced in the sandbox"
                  : overallStatus === "running"
                  ? `Step ${currentStep + 1} of ${validationSteps.length}`
                  : "Initializing validation engine"}
              </p>
            </div>
          </div>

          <div className="grid lg:grid-cols-2 gap-6">
            {/* Validation Steps */}
            <Card className="bg-background-secondary/50 border-border">
              <CardHeader>
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-primary/20 text-primary">
                    <FileText className="h-5 w-5" />
                  </div>
                  <div>
                    <CardTitle>Validation Steps</CardTitle>
                    <CardDescription>
                      Progress of exploit verification
                    </CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {validationSteps.map((step, index) => (
                    <div
                      key={step.id}
                      className={`flex items-start gap-3 p-3 rounded-lg transition-colors ${
                        step.status === "running"
                          ? "bg-primary/10 border border-primary/30"
                          : step.status === "success"
                          ? "bg-success/5"
                          : "bg-transparent"
                      }`}
                    >
                      <div className="mt-0.5">{getStatusIcon(step.status)}</div>
                      <div className="flex-1">
                        <p
                          className={`text-sm font-medium ${
                            step.status === "success"
                              ? "text-success"
                              : step.status === "running"
                              ? "text-primary"
                              : "text-foreground"
                          }`}
                        >
                          {step.name}
                        </p>
                        <p className="text-xs text-foreground-muted">
                          {step.description}
                        </p>
                      </div>
                      {step.status === "success" && (
                        <span className="text-xs text-success">✓</span>
                      )}
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>

            {/* Live Logs */}
            <Card className="bg-background-secondary/50 border-border">
              <CardHeader>
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-info/20 text-info">
                    <Terminal className="h-5 w-5" />
                  </div>
                  <div>
                    <CardTitle>Live Logs</CardTitle>
                    <CardDescription>
                      Real-time validation output
                    </CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="rounded-lg bg-black/60 p-4 border border-white/10 font-mono text-xs h-[300px] overflow-y-auto">
                  {logs.map((log, index) => (
                    <div
                      key={index}
                      className={`py-0.5 ${
                        log.includes("complete") ||
                        log.includes("success") ||
                        log.includes("VERIFIED")
                          ? "text-green-400"
                          : log.includes("error") || log.includes("failed")
                          ? "text-red-400"
                          : log.includes("IronWall")
                          ? "text-cyan-400"
                          : "text-gray-300"
                      }`}
                    >
                      {log}
                    </div>
                  ))}
                  {overallStatus === "running" && (
                    <div className="text-primary animate-pulse">▌</div>
                  )}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Results Card - Show when complete */}
          {overallStatus === "success" && (
            <Card className="bg-success/5 border-success/30 animate-fade-in">
              <CardHeader>
                <div className="flex items-center gap-3">
                  <div className="p-2 rounded-lg bg-success/20 text-success">
                    <CheckCircle className="h-5 w-5" />
                  </div>
                  <div>
                    <CardTitle className="text-success">
                      Validation Complete
                    </CardTitle>
                    <CardDescription>
                      Exploit has been verified in the sandbox environment
                    </CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid md:grid-cols-3 gap-4">
                  <div className="p-4 rounded-lg bg-background-secondary border border-border">
                    <p className="text-xs text-foreground-muted mb-1">Status</p>
                    <p className="text-lg font-semibold text-success">
                      VERIFIED
                    </p>
                  </div>
                  <div className="p-4 rounded-lg bg-background-secondary border border-border">
                    <p className="text-xs text-foreground-muted mb-1">
                      Crash Address
                    </p>
                    <p className="text-lg font-semibold font-mono">
                      0x41414141
                    </p>
                  </div>
                  <div className="p-4 rounded-lg bg-background-secondary border border-border">
                    <p className="text-xs text-foreground-muted mb-1">
                      Execution Time
                    </p>
                    <p className="text-lg font-semibold">2.34s</p>
                  </div>
                </div>
              </CardContent>
              <CardFooter className="flex gap-4">
                <Button
                  variant="outline"
                  className="gap-2 border-success bg-success/10 text-success hover:bg-success/20"
                  onClick={handleDownloadReport}
                >
                  <Download className="h-4 w-4" />
                  Download Report
                </Button>
                <Button
                  variant="outline"
                  className="gap-2"
                  onClick={() => navigate("/dashboard")}
                >
                  Back to Dashboard
                </Button>
              </CardFooter>
            </Card>
          )}
        </div>
      </main>
    </div>
  );
}
